app:
  port: 9999
  host: 0.0.0.0

db:
    migrationsSourceURL: file://migrations
    hostname: localhost
    port: 5900
    username: app
    password: pass
    databaseName: test

keycloak:
  host: host
  clientId: clientId
  clientSecret: clientSecret
  realm: realm